### ISSUE TITLE
Reset Form Validation in Functional Component

### ISSUE THREAD

**Issue by AkshatK805** [NewOldMax/react-material-ui-form-validator#185]
I'm trying to reset form validations in a functional component on click of button the validations are resetting but I'm getting an error.

What I'm doing is :- 
const resetValidations = useRef();

const handleReset = () => {
        resetValidations.current.resetValidations();
      };

<ValidatorForm ref = {resetValidations} instantValidate= {false} onSubmit={handleSubmit}>

I'm calling handleReset on click of a button and I'm getting this :- 

Uncaught TypeError: Cannot read properties of undefined (reading 'visibilityCheck')
    at a (preload-content.js:3:6673)
    at e.searchUsernameField (preload-content.js:3:6726)
    at e.onDomUpdate (preload-content.js:3:6239)
    at Object.onChange (preload-content.js:3:6987)
    at g (preload-content.js:3:5488)
    at MutationObserver.d (preload-content.js:3:5399)

Can anyone help me on this?

**Comment by AkshatK805** [comment]
Resolved
